In [1]:
transfomed_train_file_path = r"C:\Users\Asus\ML_Projects\Black_Friday_Sales_Prediction\black_friday\artifact\data_transformation\2023-02-18_12-03-50\transformed_data\transformed_train_dir\black_friday_train_data.npz"

In [2]:
import numpy as np

In [3]:
with open(transfomed_train_file_path, "rb") as file:
    k = np.load(file, allow_pickle=True)

In [4]:
k

array([[1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 8.0000e+00,
        3.8860e+03],
       [1.0000e+00, 1.0000e+00, 0.0000e+00, ..., 1.0000e+00, 1.6000e+01,
        1.2148e+04],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 8.0000e+00,
        8.0540e+03],
       ...,
       [0.0000e+00, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 5.0000e+00,
        6.9540e+03],
       [0.0000e+00, 1.0000e+00, 0.0000e+00, ..., 0.0000e+00, 8.0000e+00,
        6.1510e+03],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.0000e+00, 5.0000e+00,
        7.1460e+03]])

In [5]:
input_x = k[:, :-1]
output_x = k[:, -1]

In [6]:
input_x

array([[ 1.,  0.,  0., ..., 16.,  0.,  8.],
       [ 1.,  1.,  0., ...,  1.,  1., 16.],
       [ 1.,  0.,  0., ...,  7.,  0.,  8.],
       ...,
       [ 0.,  1.,  0., ...,  1.,  0.,  5.],
       [ 0.,  1.,  0., ...,  4.,  0.,  8.],
       [ 0.,  0.,  0., ...,  2.,  1.,  5.]])

In [7]:
output_x

array([ 3886., 12148.,  8054., ...,  6954.,  6151.,  7146.])

In [8]:
transfomed_test_file_path = r"C:\Users\Asus\ML_Projects\Black_Friday_Sales_Prediction\black_friday\artifact\data_transformation\2023-02-18_12-03-50\transformed_data\transformed_test_dir\black_friday_test_data.npz"

In [9]:
with open(transfomed_test_file_path, "rb") as file:
    l = np.load(file, allow_pickle=True)

In [10]:
input_y = l[:, :-1]
output_y = l[:, -1]

# Linear Regression

In [11]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [12]:
model.fit(input_x, output_x)

LinearRegression()

In [13]:
output_pred_x = model.predict(input_x)

In [14]:
from sklearn.metrics import r2_score

In [15]:
r2_score(output_x, output_pred_x)

0.13208548535515485

In [16]:
output_pred_y = model.predict(input_y)

In [17]:
r2_score(output_y, output_pred_y)

0.12927310647633417

# Ridge Regression

In [18]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [19]:
ridge = Ridge()
model = GridSearchCV(ridge, param_grid={'alpha' : [0.1, 0.5, 0.8]}, cv=5, verbose=True)

In [20]:
model.fit(input_x, output_x)

Fitting 5 folds for each of 3 candidates, totalling 15 fits


GridSearchCV(cv=5, estimator=Ridge(), param_grid={'alpha': [0.1, 0.5, 0.8]},
             verbose=True)

In [21]:
output_pred_x = model.predict(input_x)

In [22]:
r2_score(output_x, output_pred_x)

0.13208548535421039

In [23]:
output_pred_y = model.predict(input_y)

In [24]:
r2_score(output_y, output_pred_y)

0.12927310374449397

In [25]:
model.best_params_

{'alpha': 0.8}

# Lasso

In [26]:
from sklearn.linear_model import Lasso

lasso = Lasso()

model = GridSearchCV(lasso, param_grid={'alpha' : [0.1, 0.5, 0.8]}, cv=5, verbose=True)

In [27]:
model.fit(input_x, output_x)

Fitting 5 folds for each of 3 candidates, totalling 15 fits


GridSearchCV(cv=5, estimator=Lasso(), param_grid={'alpha': [0.1, 0.5, 0.8]},
             verbose=True)

In [28]:
output_pred_x = model.predict(input_x)

In [29]:
r2_score(output_x, output_pred_x)

0.1320854725462305

In [30]:
output_pred_y = model.predict(input_y)

In [31]:
r2_score(output_y, output_pred_y)

0.12927280190272505

In [32]:
model.best_params_

{'alpha': 0.1}

# Elastic

In [33]:
from sklearn.linear_model import ElasticNet

elastic = ElasticNet()

model = GridSearchCV(elastic, param_grid={'alpha' : [0.1, 0.5, 0.8]}, cv=5, verbose=True)

In [34]:
model.fit(input_x, output_x)

Fitting 5 folds for each of 3 candidates, totalling 15 fits


GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 0.5, 0.8]}, verbose=True)

In [35]:
output_pred_x = model.predict(input_x)

In [36]:
r2_score(output_x, output_pred_x)

0.1318110626081438

In [37]:
output_pred_y = model.predict(input_y)

In [38]:
r2_score(output_y, output_pred_y)

0.12895329872862082

In [39]:
model.best_params_

{'alpha': 0.1}

# Decison Tree

In [40]:
from sklearn.tree import DecisionTreeRegressor

decision = DecisionTreeRegressor()

model = GridSearchCV(decision, param_grid={'max_depth':[9,11,13,15,17],
          'min_samples_leaf':[7,9,11,13],
          'min_samples_split':[8,10,12,14]}, cv = 5, verbose=True)

In [41]:
model.fit(input_x, output_x)

Fitting 5 folds for each of 80 candidates, totalling 400 fits


GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'max_depth': [9, 11, 13, 15, 17],
                         'min_samples_leaf': [7, 9, 11, 13],
                         'min_samples_split': [8, 10, 12, 14]},
             verbose=True)

In [42]:
output_pred_x = model.predict(input_x)

In [43]:
r2_score(output_x, output_pred_x)

0.6627249504296288

In [44]:
output_pred_y = model.predict(input_y)

In [45]:
r2_score(output_y, output_pred_y)

0.6503577935583364

In [46]:
model.best_estimator_

DecisionTreeRegressor(max_depth=11, min_samples_leaf=13, min_samples_split=8)

In [47]:
model.best_estimator_

DecisionTreeRegressor(max_depth=11, min_samples_leaf=13, min_samples_split=8)

In [65]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

rf = RandomForestRegressor()

model = GridSearchCV(rf,
                    param_grid={
                        'n_estimators' : [100, 110, 120],
                        'max_depth' : [2,4,8],
                        'min_samples_split' : [2,4,6]}, verbose=2)
model.fit(input_x, output_x)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV] END .max_depth=2, min_samples_split=2, n_estimators=100; total time=  13.9s
[CV] END .max_depth=2, min_samples_split=2, n_estimators=100; total time=  13.8s
[CV] END .max_depth=2, min_samples_split=2, n_estimators=100; total time=  14.5s
[CV] END .max_depth=2, min_samples_split=2, n_estimators=100; total time=  15.1s
[CV] END .max_depth=2, min_samples_split=2, n_estimators=100; total time=  15.6s
[CV] END .max_depth=2, min_samples_split=2, n_estimators=110; total time=  15.7s
[CV] END .max_depth=2, min_samples_split=2, n_estimators=110; total time=  16.8s
[CV] END .max_depth=2, min_samples_split=2, n_estimators=110; total time=  15.7s
[CV] END .max_depth=2, min_samples_split=2, n_estimators=110; total time=  16.2s
[CV] END .max_depth=2, min_samples_split=2, n_estimators=110; total time=  16.6s
[CV] END .max_depth=2, min_samples_split=2, n_estimators=120; total time=  16.4s
[CV] END .max_depth=2, min_samples_split=2, n_e

[CV] END .max_depth=8, min_samples_split=2, n_estimators=120; total time=  50.1s
[CV] END .max_depth=8, min_samples_split=2, n_estimators=120; total time=  50.8s
[CV] END .max_depth=8, min_samples_split=2, n_estimators=120; total time=  43.2s
[CV] END .max_depth=8, min_samples_split=2, n_estimators=120; total time=  39.7s
[CV] END .max_depth=8, min_samples_split=4, n_estimators=100; total time=  33.8s
[CV] END .max_depth=8, min_samples_split=4, n_estimators=100; total time=  36.9s
[CV] END .max_depth=8, min_samples_split=4, n_estimators=100; total time=  32.9s
[CV] END .max_depth=8, min_samples_split=4, n_estimators=100; total time=  33.3s
[CV] END .max_depth=8, min_samples_split=4, n_estimators=100; total time=  34.0s
[CV] END .max_depth=8, min_samples_split=4, n_estimators=110; total time=  38.7s
[CV] END .max_depth=8, min_samples_split=4, n_estimators=110; total time=  44.1s
[CV] END .max_depth=8, min_samples_split=4, n_estimators=110; total time=  37.4s
[CV] END .max_depth=8, min_s

GridSearchCV(estimator=RandomForestRegressor(),
             param_grid={'max_depth': [2, 4, 8], 'min_samples_split': [2, 4, 6],
                         'n_estimators': [100, 110, 120]},
             verbose=2)

In [66]:
output_x_pred = model.predict(input_x)

In [67]:
from sklearn.metrics import r2_score
r2_score(output_x, output_x_pred)

0.6554861910300241

In [68]:
output_y_pred = model.predict(input_y)

In [69]:
r2_score(output_y, output_y_pred)

0.6483787660647703

In [70]:
model.best_estimator_

RandomForestRegressor(max_depth=8, min_samples_split=4)

In [71]:
from sklearn.metrics import mean_squared_error

In [72]:
mean_squared_error(output_x,  output_x_pred)

8696731.536157524

In [73]:
model.best_score_

0.6538912325331239

In [74]:
model.best_params_

{'max_depth': 8, 'min_samples_split': 4, 'n_estimators': 100}

In [25]:
from xgboost import XGBRegressor

regressor = XGBRegressor()

In [51]:
from sklearn.model_selection import GridSearchCV
params={
    "learning_rate"    : [0.2, 0.25, 0.35, 0.45] ,
    "max_depth"        : [ 8, 10, 12],
    "n_estimators" : [100, 110, 120]
}

In [52]:
model = GridSearchCV(regressor, param_grid=params, verbose=2, cv=5)

In [53]:
model.fit(input_x, output_x)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=100; total time=   7.2s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=100; total time=   7.2s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=100; total time=   7.6s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=100; total time=   7.1s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=100; total time=   7.3s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=110; total time=   8.5s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=110; total time=   8.3s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=110; total time=   8.5s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=110; total time=   8.7s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=110; total time=   8.4s
[CV] END ...learning_rate=0.2, max_depth=8, n_estimators=120; total time=   9.1s
[CV] END ...learning_rate=0.2, max_depth=8, n_e

[CV] END ..learning_rate=0.35, max_depth=8, n_estimators=120; total time=   9.3s
[CV] END ..learning_rate=0.35, max_depth=8, n_estimators=120; total time=   9.4s
[CV] END ..learning_rate=0.35, max_depth=8, n_estimators=120; total time=   9.3s
[CV] END ..learning_rate=0.35, max_depth=8, n_estimators=120; total time=   9.3s
[CV] END .learning_rate=0.35, max_depth=10, n_estimators=100; total time=  10.3s
[CV] END .learning_rate=0.35, max_depth=10, n_estimators=100; total time=  10.3s
[CV] END .learning_rate=0.35, max_depth=10, n_estimators=100; total time=  10.3s
[CV] END .learning_rate=0.35, max_depth=10, n_estimators=100; total time=  10.3s
[CV] END .learning_rate=0.35, max_depth=10, n_estimators=100; total time=  10.3s
[CV] END .learning_rate=0.35, max_depth=10, n_estimators=110; total time=  11.3s
[CV] END .learning_rate=0.35, max_depth=10, n_estimators=110; total time=  11.4s
[CV] END .learning_rate=0.35, max_depth=10, n_estimators=110; total time=  11.4s
[CV] END .learning_rate=0.35

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, gamma=None, gpu_id=None,
                                    grow_policy=None, importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, m...
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
          

In [54]:
output_pred_x = model.predict(input_x)

In [55]:
from sklearn.metrics import r2_score
r2_score(output_x, output_pred_x)

0.6978038934958275

In [56]:
output_pred_y = model.predict(input_y)

In [57]:
r2_score(output_y, output_pred_y)

0.6720028869779229

In [58]:
model.best_params_

{'learning_rate': 0.2, 'max_depth': 8, 'n_estimators': 120}

In [60]:
from sklearn.svm import SVR
model = SVR(verbose=2)

In [ ]:
model.fit(input_x, output_x)

[LibSVM]